import Head from "next/head";
import React, { useState, useEffect } from "react";
import styles from "@/styles/Home.module.css";
import Header from "@/layouts/Header";
import Authentication from "@/layouts/Authentication";
import Appinput from "@/layouts/Appinput";
import PasswordInput from "@/layouts/PasswordInput";
import FormButton from "@/layouts/FormButton";
import { CiSearch } from "react-icons/ci";
import SearchInput from "@/layouts/SearchInput";
import Axios from "axios";
export default function Home() {
  const [product, setProducts] = useState();

  //usestate to add cart items

  const [cart, setCart] = useState([]);
  const [cartCount, setCartCount] = useState(0);

  const token =
    typeof window !== "undefined" ? window.localStorage.getItem("token") : null;

  const config = {
    headers: {
      Authorization: `Bearer ${token && token}`,
    },
  };
  useEffect(() => {
    Axios.get("http://localhost:2000/products/getProducts", config)
      .then((response) => {
        setProducts(response?.data?.getProducts);
      })
      .catch((err) => {
        err?.response?.code ||
          (err?.response?.code === 500 && "") ||
          // console.error(err?.message);
          alert(err?.message);
      });
  }, []);
  console.log(product);

  function addToCart(product) {
    const isProductInCart = cart?.some((item) => item.id === product.id);
    if (isProductInCart) {
      return;
    }
    const updatedCart = [...cart, product];
    setCart(updatedCart);
    setCartCount(updatedCart.length);
    localStorage.setItem("UserData", JSON.stringify(updatedCart));
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header title="Admin" content="products" />

      <SearchInput />
      <div className={styles.container}>
        {product?.length === 0 ? <p>You need to create an account</p> : ""}
        <div className={styles.topProduct}>
          {product?.map((p) => {
            return (
              <div className={styles.content}>
                <img src={`http://localhost:2000/${p?.profile_url}`} />
                <p>{p?.title}</p>
                <p>{p?.price}</p>
                <button onClick={() => addToCart(product)}>Add to cart</button>
              </div>
            );
          })}
        </div>
      </div>
    </>
  );
}
